In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics

In [2]:
data = pd.read_pickle('data/bank_data_dummies.pkl')
data1 = data.drop(columns=['y'], axis=1)

x = np.ones([len(data1),len(list(data1))+1])
y = np.ones([len(data1)])

x[:,1:len(list(data1))+1] = data1[:]


for i in range(len(data)):
    y[i] = data['y'][i]

x_train = x[:int(0.7*len(data))]
y_train = y[:int(0.7*len(data))]
x_test = x[int(0.7*len(data)):]
y_test = y[int(0.7*len(data)):]


In [3]:
c=0
d=0
for i in range(len(x_train)):
    if y_train[i]==1:
        c+=1
    else:
        d+=1
        
print('No. of positive values before sampling: {} '.format(c))
print('No. of negative values before sampling: {} '.format(d))
print()
x_train_sampled = np.ones([len(x_train)+16*c,x_train.shape[1]])
y_train_sampled = np.ones([len(y_train)+16*c])
x_train_sampled[:len(x_train)]= x_train[:]
y_train_sampled[:len(y_train)]= y_train[:]

m1 = len(x_train)
for i in range(len(x_train)):
    if y_train[i]==1:
        for j in range(16):
            x_train_sampled[m1]=x_train[i]
            y_train_sampled[m1]=y_train[i]
            m1+=1

c=0
d=0
for i in range(len(x_train_sampled)):
    if y_train_sampled[i]==1:
        c+=1
    else:
        d+=1

print('No. of positive values after sampling: {} '.format(c))
print('No. of negative values after sampling: {} '.format(d))

No. of positive values before sampling: 1840 
No. of negative values before sampling: 29807 

No. of positive values after sampling: 31280 
No. of negative values after sampling: 29807 


In [ ]:
svc = svm.SVC(kernel='poly', degree=3, gamma='scale',C=1)
svc.fit(x_train_sampled, y_train_sampled.ravel())

In [5]:
predictions = svc.predict(x_test)

print(metrics.confusion_matrix(y_test, predictions))

accuracy = metrics.accuracy_score(y_test, predictions)
precision = metrics.precision_score(y_test, predictions)
recall = metrics.recall_score(y_test, predictions)
f1_score = metrics.f1_score(y_test, predictions)

print("Accuracy(testing): ", accuracy)
print("Precision(testing): ", precision)
print("Recall(testing): ", recall)
print("F1 score(testing): ", f1_score)


[[5835 4280]
 [1170 2279]]
Accuracy(testing):  0.5982011206133884
Precision(testing):  0.34746150327793873
Recall(testing):  0.6607712380400116
F1 score(testing):  0.4554356514788169


In [6]:
predictions = svc.predict(x_train)
print(metrics.confusion_matrix(y_train, predictions))

accuracy = metrics.accuracy_score(y_train, predictions)
precision = metrics.precision_score(y_train, predictions)
recall = metrics.recall_score(y_train, predictions)
f1_score = metrics.f1_score(y_train, predictions)

print("Accuracy(training): ", accuracy)
print("Precision(training): ", precision)
print("Recall(training): ", recall)
print("F1 score(training): ", f1_score)

[[20824  8983]
 [  543  1297]]
Accuracy(training):  0.6989920055613487
Precision(training):  0.12616731517509727
Recall(training):  0.7048913043478261
F1 score(training):  0.214026402640264


In [7]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics

In [8]:
rf = RandomForestRegressor(n_estimators=5)
rf.fit(x_train_sampled, y_train_sampled)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=5, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [9]:
y_pred = rf.predict(x_test)
predictions = y_pred.copy()
for i in range(predictions.size):
    if(predictions[i] >= 0.48):
        predictions[i] = 1
    else:
        predictions[i] = 0
print(metrics.confusion_matrix(y_test, predictions))
accuracy = metrics.accuracy_score(y_test, predictions)
precision = metrics.precision_score(y_test, predictions)
recall = metrics.recall_score(y_test, predictions)
f1_score = metrics.f1_score(y_test, predictions)

print("Accuracy(testing): ", accuracy)
print("Precision(testing): ", precision)
print("Recall(testing): ", recall)
print("F1 score(testing): ", f1_score)

[[9644  471]
 [3163  286]]
Accuracy(testing):  0.7320849306989089
Precision(testing):  0.37780713342140027
Recall(testing):  0.08292258625688606
F1 score(testing):  0.13599619591060388


In [10]:
y_pred = rf.predict(x_train)
predictions = y_pred.copy()
for i in range(predictions.size):
    if(predictions[i] >= 0.48):
        predictions[i] = 1
    else:
        predictions[i] = 0
        
print(metrics.confusion_matrix(y_train, predictions))


accuracy = metrics.accuracy_score(y_train, predictions)
precision = metrics.precision_score(y_train, predictions)
recall = metrics.recall_score(y_train, predictions)
f1_score = metrics.f1_score(y_train, predictions)

print("Accuracy(training): ", accuracy)
print("Precision(training): ", precision)
print("Recall(training): ", recall)
print("F1 score(training): ", f1_score)

[[29715    92]
 [    0  1840]]
Accuracy(training):  0.9970929313995007
Precision(training):  0.9523809523809523
Recall(training):  1.0
F1 score(training):  0.975609756097561


In [11]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn import metrics
from sklearn.preprocessing import PolynomialFeatures

In [12]:
poly = PolynomialFeatures(2,include_bias=False)
poly.fit_transform(x_train_sampled)
lr = linear_model.LogisticRegression(solver='lbfgs', max_iter=500)
lr.fit(x_train_sampled, y_train_sampled)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=500, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [13]:
predictions = lr.predict(x_test)
print(metrics.confusion_matrix(y_test, predictions))
accuracy = metrics.accuracy_score(y_test, predictions)
precision = metrics.precision_score(y_test, predictions)
recall = metrics.recall_score(y_test, predictions)
f1_score = metrics.f1_score(y_test, predictions)

print("Accuracy(testing): ", accuracy)
print("Precision(testing): ", precision)
print("Recall(testing): ", recall)
print("F1 score(testing): ", f1_score)


[[6551 3564]
 [1410 2039]]
Accuracy(testing):  0.63329401356532
Precision(testing):  0.3639121898982688
Recall(testing):  0.5911858509712961
F1 score(testing):  0.45050817498895274


In [14]:
predictions = lr.predict(x_train)
print(metrics.confusion_matrix(y_train, predictions))

accuracy = metrics.accuracy_score(y_train, predictions)
precision = metrics.precision_score(y_train, predictions)
recall = metrics.recall_score(y_train, predictions)
f1_score = metrics.f1_score(y_train, predictions)

print("Accuracy(training): ", accuracy)
print("Precision(training): ", precision)
print("Recall(training): ", recall)
print("F1 score(training): ", f1_score)

[[19487 10320]
 [  712  1128]]
Accuracy(training):  0.6514045565140456
Precision(training):  0.09853249475890985
Recall(training):  0.6130434782608696
F1 score(training):  0.16977724262492472


In [15]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn import metrics

In [16]:
mlpc = MLPClassifier(hidden_layer_sizes=(100, 200, 100), activation='relu', solver='lbfgs', 
                     alpha=0.005, learning_rate_init=0.001, shuffle=False)
mlpc.fit(x_train_sampled, y_train_sampled)

MLPClassifier(activation='relu', alpha=0.005, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 200, 100), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=False, solver='lbfgs', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [17]:
predictions = mlpc.predict(x_test)
metrics.confusion_matrix(y_test, predictions)
accuracy = metrics.accuracy_score(y_test, predictions)
precision = metrics.precision_score(y_test, predictions)
recall = metrics.recall_score(y_test, predictions)
f1_score = metrics.f1_score(y_test, predictions)

print("Accuracy(testing): ", accuracy)
print("Precision(testing): ", precision)
print("Recall(testing): ", recall)
print("F1 score(testing): ", f1_score)

Accuracy(testing):  0.6513565319964613
Precision(testing):  0.33298538622129437
Recall(testing):  0.3699623079153378
F1 score(testing):  0.3505013047658289


In [18]:
predictions = mlpc.predict(x_train)
print(metrics.confusion_matrix(y_train, predictions))

accuracy = metrics.accuracy_score(y_train, predictions)
precision = metrics.precision_score(y_train, predictions)
recall = metrics.recall_score(y_train, predictions)
f1_score = metrics.f1_score(y_train, predictions)

print("Accuracy(training): ", accuracy)
print("Precision(training): ", precision)
print("Recall(training): ", recall)
print("F1 score(training): ", f1_score)

[[26299  3508]
 [   31  1809]]
Accuracy(training):  0.8881726545960122
Precision(training):  0.3402294526988904
Recall(training):  0.9831521739130434
F1 score(training):  0.5055190722369709
