# Regression

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn import metrics

In [2]:
df = pd.read_pickle('data/bank_data.pkl')

In [3]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['y'], axis=1), df['y'], test_size=0.3)

### Linear Regression

In [4]:
lr = linear_model.LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [5]:
predictions = y_pred.copy()
for i in range(predictions.size):
    if(predictions[i] >= 0.5):
        predictions[i] = 1
    else:
        predictions[i] = 0
metrics.confusion_matrix(y_test, predictions)

array([[11916,     0],
       [ 1648,     0]])

In [6]:
accuracy = metrics.accuracy_score(y_test, predictions)
precision = metrics.precision_score(y_test, predictions)
recall = metrics.recall_score(y_test, predictions)
f1_score = metrics.f1_score(y_test, predictions)

print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 score: ", f1_score)

Accuracy:  0.8785019168386906
Precision:  0.0
Recall:  0.0
F1 score:  0.0


/Users/arunjoseph/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/arunjoseph/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


### Ridge Regression

In [7]:
lr = linear_model.Ridge()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [8]:
predictions = y_pred.copy()
for i in range(predictions.size):
    if(predictions[i] >= 0.3):
        predictions[i] = 1
    else:
        predictions[i] = 0
metrics.confusion_matrix(y_test, predictions)

array([[11916,     0],
       [ 1648,     0]])

In [9]:
accuracy = metrics.accuracy_score(y_test, predictions)
precision = metrics.precision_score(y_test, predictions)
recall = metrics.recall_score(y_test, predictions)
f1_score = metrics.f1_score(y_test, predictions)

print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 score: ", f1_score)

Accuracy:  0.8785019168386906
Precision:  0.0
Recall:  0.0
F1 score:  0.0


/Users/arunjoseph/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/arunjoseph/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


### Lasso Regression

In [10]:
lr = linear_model.Lasso(alpha=0.1)
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [11]:
predictions = y_pred.copy()
for i in range(predictions.size):
    if(predictions[i] >= 0.5):
        predictions[i] = 1
    else:
        predictions[i] = 0
metrics.confusion_matrix(y_test, predictions)

array([[11916,     0],
       [ 1648,     0]])

In [12]:
accuracy = metrics.accuracy_score(y_test, predictions)
precision = metrics.precision_score(y_test, predictions)
recall = metrics.recall_score(y_test, predictions)
f1_score = metrics.f1_score(y_test, predictions)

print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 score: ", f1_score)

Accuracy:  0.8785019168386906
Precision:  0.0
Recall:  0.0
F1 score:  0.0


/Users/arunjoseph/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/arunjoseph/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


### Elastic Net Regression

In [13]:
lr = linear_model.ElasticNet()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [14]:
predictions = y_pred.copy()
for i in range(predictions.size):
    if(predictions[i] >= 0.5):
        predictions[i] = 1
    else:
        predictions[i] = 0
metrics.confusion_matrix(y_test, predictions)

array([[11916,     0],
       [ 1648,     0]])

In [15]:
accuracy = metrics.accuracy_score(y_test, predictions)
precision = metrics.precision_score(y_test, predictions)
recall = metrics.recall_score(y_test, predictions)
f1_score = metrics.f1_score(y_test, predictions)

print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 score: ", f1_score)

Accuracy:  0.8785019168386906
Precision:  0.0
Recall:  0.0
F1 score:  0.0


/Users/arunjoseph/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/arunjoseph/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


### Logistic Regression

In [16]:
lr = linear_model.LogisticRegression(solver='lbfgs', max_iter=500)
lr.fit(X_train, y_train)
predictions = lr.predict(X_test)

In [17]:
metrics.confusion_matrix(y_test, predictions)

array([[11916,     0],
       [ 1648,     0]])

In [18]:
accuracy = metrics.accuracy_score(y_test, predictions)
precision = metrics.precision_score(y_test, predictions)
recall = metrics.recall_score(y_test, predictions)
f1_score = metrics.f1_score(y_test, predictions)

print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 score: ", f1_score)

Accuracy:  0.8785019168386906
Precision:  0.0
Recall:  0.0
F1 score:  0.0


/Users/arunjoseph/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/arunjoseph/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
